### PR TITLE
github actions for multi-arch builds

### PR DESCRIPTION
**Pull request by Just5KY**
Create a GitHub secret with the name `DOCKER_TOKEN` and add your docker-hub access token to it.

### CODE REVIEW

**Comment by martadinata666** [comment]
Some consideration
1. Change main to `develop`, as stable/main use tag version `vX.Y.Z` and develop as rolling release one.
2. Add qemu before buildx.
```
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

```
3. Docker login using actions. Like for reusability
```
-
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```
4. Use meta and build push, practically just tag conditioning
```
# https://github.com/docker/metadata-action
-       name: Docker meta
        id: <themetaname>
        uses: docker/metadata-action@v3
        with:
          images: <the image name>
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
-       name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} #push except PR.
          tags: ${{ steps.<themetaname>.outputs.tags }}
          labels: ${{ steps.<themetaname>.outputs.labels }}
```

**Comment by Just5KY** [comment]
Don't really need QEMU, GitHub support multiarch images by default

**Comment by martadinata666** [comment]
Really? cant really make it to run, https://github.com/martadinata666/goaccess-for-nginxproxymanager/actions/runs/2043113126

**Comment by Just5KY** [comment]
@martadinata666 thanks, I added QEMU.

```Inspect builder
  {
    "name": "builder-2a695eea-186a-4b5e-a061-c5cded613a82",
    "driver": "docker-container",
    "node_name": "builder-2a695eea-186a-4b5e-a061-c5cded613a820",
    "node_endpoint": "unix:///var/run/docker.sock",
    "node_status": "running",
    "node_flags": "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host",
    "node_platforms": "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6"
  }
```

For some reason,  it worked out of the box for another test repo I was testing in
https://github.com/Just5KY/scalyr-tool/runs/5697565469?check_suite_focus=true
I will add

**Comment by martadinata666** [comment]
> @martadinata666 thanks, I added QEMU.
> 
> ```
>   {
>     "name": "builder-2a695eea-186a-4b5e-a061-c5cded613a82",
>     "driver": "docker-container",
>     "node_name": "builder-2a695eea-186a-4b5e-a061-c5cded613a820",
>     "node_endpoint": "unix:///var/run/docker.sock",
>     "node_status": "running",
>     "node_flags": "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host",
>     "node_platforms": "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6"
>   }
> ```
> 
> For some reason, it worked out of the box for another test repo I was testing in https://github.com/Just5KY/scalyr-tool/runs/5697565469?check_suite_focus=true I will add

Because it doesnt do anything, `ADD` itself from use internal docker function to fetch files, so basically it just repacking. THe manifest itself will overwrite each other i assume.

**Comment by xavier-hernandez** [comment]
I looked this over and tested it on a different repo and it appears to be working correctly. 

However, I found that it builds from scratch every time. It takes about 6 minutes. It's not horrible but I was looking into using caching on the docker layers. I implemented the following code on my other repo. It seems to work. Let me know what you guys think.

https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md

@Just5KY @martadinata666 

```code
name: Main branch build & push

on:
  #schedule:
  #  - cron: '50 15 * * *'  #Change this to when you want automatic builds
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: goaccess-for-nginxproxymanager

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: xavierh/goaccess-for-nginxproxymanager:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

**Comment by martadinata666** [comment]
the considertion with cache is, it using cached version instead newest image. Ex  we use `alpine:3.15 AS builder` as this rarely changed, `alpine3.15` today not the same `alpine3.15` upstream if upstream got update. Personally not a fan of this.

`setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf"` it just version revision.

My workflows, using consideration i mention above
```
name: Docker Image Build

on:
  push:
    branches: [ 'develop' ] #rolling build on develop only
    tags: 'v*' #tag for specific release v1.0.2,or anytag, start with v
  pull_request:
    branches: [ 'main' ] #build test on main, not pushing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker meta
        id: metaid
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/goaccess-nginx-proxy-manager
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-
            
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} #push except PR.
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.metaid.outputs.tags }}
          labels: ${{ steps.metaid.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          
#      - name: Move cache
#        run: |
#          rm -rf /tmp/.buildx-cache
#          mv /tmp/.buildx-cache-new /tmp/.buildx-cache



```

**Comment by Just5KY** [comment]
i updated the docker action and changed `setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf` with `setup-buildx-action@v1`
since they both were doing the same thing

**Comment by xavier-hernandez** [comment]
@Just5KY I'll get to this in a couple of days. I already confirmed that everything works.

**Comment by Just5KY** [comment]
Yes it works
I push images to my dockerhub using this for the latest version

**Comment by martadinata666** [comment]
Only need `:latest` tag?  🤔 
Isn't usually
`v1.0` `latest`
then
`v1.1` `latest`
So there will be roll back to prev image in case errored out. Well, it depends on your need, if it suit you, it ok. 👍🏼

**Comment by Just5KY** [comment]
@martadinata666 i am not really good with variables, if you can edit that part

**Pull request merged**
